export const DEFAULT_COMPONENTS = [
  {
    category: 'cpu',
    name: 'Intel Core i5-12600K',
    brand: 'Intel',
    price: 2500000,
    power: 125,
    stock: 18,
    description: 'Balanced gaming and productivity CPU for mid-range builds.',
    highlights: ['10 cores', 'LGA1700', 'Unlocked'],
  },
  {
    category: 'cpu',
    name: 'AMD Ryzen 5 5600X',
    brand: 'AMD',
    price: 2200000,
    power: 105,
    stock: 22,
    description: 'Efficient AM4 processor with strong gaming performance.',
    highlights: ['6 cores', 'AM4', 'DDR4 ready'],
  },
  {
    category: 'cpu',
    name: 'Intel Core i7-12700K',
    brand: 'Intel',
    price: 3500000,
    power: 190,
    stock: 11,
    description: 'High-performance CPU for heavier workloads and premium gaming.',
    highlights: ['12 cores', 'LGA1700', 'Unlocked'],
  },
  {
    category: 'gpu',
    name: 'NVIDIA RTX 3060',
    brand: 'NVIDIA',
    price: 8000000,
    power: 170,
    stock: 9,
    description: 'Reliable 1080p to 1440p graphics card.',
    highlights: ['12GB VRAM', 'Ray tracing', 'DLSS'],
  },
  {
    category: 'gpu',
    name: 'AMD RX 6700 XT',
    brand: 'AMD',
    price: 7500000,
    power: 250,
    stock: 7,
    description: 'Strong raster performance for competitive gaming builds.',
    highlights: ['12GB VRAM', 'PCIe 4.0', '1440p focused'],
  },
  {
    category: 'gpu',
    name: 'NVIDIA RTX 3070',
    brand: 'NVIDIA',
    price: 10000000,
    power: 220,
    stock: 5,
    description: 'Premium GPU choice for high-refresh 1440p gameplay.',
    highlights: ['8GB VRAM', 'Ray tracing', 'High refresh 1440p'],
  },
  {
    category: 'motherboard',
    name: 'ASUS ROG Strix B550-F',
    brand: 'ASUS',
    price: 3000000,
    power: 25,
    stock: 12,
    description: 'AM4 motherboard with solid VRM and expansion options.',
    highlights: ['AM4', 'ATX', 'PCIe 4.0'],
  },
  {
    category: 'motherboard',
    name: 'MSI MAG B660 Tomahawk',
    brand: 'MSI',
    price: 2500000,
    power: 25,
    stock: 10,
    description: 'Feature-rich Intel motherboard for value-focused builds.',
    highlights: ['LGA1700', 'ATX', 'DDR4'],
  },
  {
    category: 'ram',
    name: 'Corsair Vengeance 16GB DDR4',
    brand: 'Corsair',
    price: 800000,
    power: 3,
    stock: 30,
    description: 'Affordable dual-channel memory kit for mainstream systems.',
    highlights: ['16GB', 'DDR4', '3200MHz'],
  },
  {
    category: 'ram',
    name: 'G.Skill Ripjaws 32GB DDR4',
    brand: 'G.Skill',
    price: 1500000,
    power: 6,
    stock: 16,
    description: 'Higher-capacity memory kit for creators and multitasking.',
    highlights: ['32GB', 'DDR4', '3600MHz'],
  },
  {
    category: 'storage',
    name: 'Samsung 970 EVO 1TB NVMe',
    brand: 'Samsung',
    price: 1500000,
    power: 5,
    stock: 21,
    description: 'Fast NVMe SSD for OS, games, and production apps.',
    highlights: ['1TB', 'NVMe', 'High endurance'],
  },
  {
    category: 'storage',
    name: 'WD Blue 2TB HDD',
    brand: 'Western Digital',
    price: 800000,
    power: 8,
    stock: 26,
    description: 'Large-capacity storage for archives and mass game libraries.',
    highlights: ['2TB', '7200RPM', 'SATA'],
  },
  {
    category: 'psu',
    name: 'Corsair RM750x',
    brand: 'Corsair',
    price: 2000000,
    power: 750,
    stock: 14,
    description: 'Reliable fully modular PSU for mid to high-end builds.',
    highlights: ['750W', '80+ Gold', 'Fully modular'],
  },
  {
    category: 'psu',
    name: 'EVGA SuperNOVA 650',
    brand: 'EVGA',
    price: 1500000,
    power: 650,
    stock: 13,
    description: 'Quality PSU option for balanced gaming systems.',
    highlights: ['650W', '80+ Gold', 'Compact'],
  },
  {
    category: 'case',
    name: 'Fractal Design Meshify C',
    brand: 'Fractal Design',
    price: 1500000,
    power: 0,
    stock: 8,
    description: 'Airflow-focused case with clean cable management.',
    highlights: ['ATX Mid Tower', 'High airflow', 'Tempered glass'],
  },
  {
    category: 'case',
    name: 'Corsair 4000D Airflow',
    brand: 'Corsair',
    price: 1200000,
    power: 0,
    stock: 17,
    description: 'Well-rounded case with strong thermals and modern layout.',
    highlights: ['ATX Mid Tower', 'Mesh front', 'Cable routing'],
  },
  {
    category: 'cooler',
    name: 'Noctua NH-D15',
    brand: 'Noctua',
    price: 1500000,
    power: 10,
    stock: 9,
    description: 'Flagship air cooler for quiet and efficient CPU cooling.',
    highlights: ['Dual tower', 'Quiet operation', 'High compatibility'],
  },
  {
    category: 'cooler',
    name: 'Corsair H100i Elite Capellix',
    brand: 'Corsair',
    price: 2000000,
    power: 20,
    stock: 6,
    description: '240mm AIO cooler for premium thermal performance.',
    highlights: ['240mm radiator', 'RGB', 'AIO liquid cooler'],
  },
  {
    category: 'fan',
    name: 'Corsair ML120 Pro',
    brand: 'Corsair',
    price: 400000,
    power: 2,
    stock: 24,
    description: 'High static pressure fan for radiators and airflow tuning.',
    highlights: ['120mm', 'Magnetic levitation', 'Quiet'],
  },
  {
    category: 'fan',
    name: 'Noctua NF-F12',
    brand: 'Noctua',
    price: 350000,
    power: 2,
    stock: 20,
    description: 'Proven 120mm fan with low noise and steady airflow.',
    highlights: ['120mm', 'PWM', 'Low noise'],
  },
];

export async function seedComponentsIfNeeded(ComponentModel) {
  const count = await ComponentModel.countDocuments();
  if (count > 0) {
    return;
  }

  await ComponentModel.insertMany(DEFAULT_COMPONENTS);
  console.log(`✓ Seeded ${DEFAULT_COMPONENTS.length} components`);
}